# Generated by Django 4.1 on 2023-08-04 09:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9ba93b51-93fb-41e7-92d8-d4f19aeb668f'), editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('show', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('fb1ceb9e-1c20-4284-abae-b1831533f3df'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('81c6dc9d-7faa-4c62-837a-eaf864dd0ef2'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('60773462-98bc-4aa9-880e-9da86ec03131'), editable=False, primary_key=True, serialize=False)),
                ('logo_path', models.ImageField(upload_to='logos/')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f60e6489-5305-45e6-8724-1ab7dcebcd4e'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('degree', models.TextField()),
                ('ssau_ref', models.URLField()),
                ('photo', models.ImageField(upload_to='speakers/')),
                ('info', models.TextField()),
                ('phrase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('3ec324ee-9cec-4048-9783-169c615b8f27'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo_path', models.ImageField(upload_to='logos/')),
                ('duration', models.PositiveIntegerField()),
                ('hours', models.PositiveIntegerField()),
                ('language', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start', models.DateField()),
                ('diploma_path', models.ImageField(upload_to='diplomas/')),
                ('skills', models.TextField()),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.direction')),
            ],
        ),
    ]
