# Generated by Django 4.1 on 2023-08-05 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10887a86-8711-410c-af2f-31595540501e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='direction',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2a0b7338-333c-4dd6-80dc-6bdca1dda4c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.UUIDField(default=uuid.UUID('79adee34-fbdc-4615-9c1e-f51d1d4d8d57'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='socials',
            name='id',
            field=models.UUIDField(default=uuid.UUID('252702af-baa3-4782-bfb0-baa4a2c78d81'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='id',
            field=models.UUIDField(default=uuid.UUID('228e47ac-49dc-42df-a8be-30b47f0a0752'), editable=False, primary_key=True, serialize=False),
        ),
    ]
