# Generated by Django 4.1 on 2023-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_advantage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='diagram_path',
            field=models.ImageField(null=True, upload_to='diagrams/'),
        ),
        migrations.AddField(
            model_name='course',
            name='for_whom_1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='for_whom_2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='for_whom_3',
            field=models.TextField(null=True),
        ),
    ]
