# Generated by Django 4.1 on 2023-09-05 05:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_remove_course_speaker_module_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='for_whom_1',
        ),
        migrations.RemoveField(
            model_name='course',
            name='for_whom_2',
        ),
        migrations.RemoveField(
            model_name='course',
            name='for_whom_3',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.AddField(
            model_name='course',
            name='description_file',
            field=models.FileField(null=True, upload_to='descriptions/'),
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.course')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=127)),
                ('mail', models.CharField(max_length=127)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.course')),
            ],
        ),
    ]
