# Generated by Django 4.1 on 2023-09-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_comment_author_comment_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='mail',
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
